name: Test Python Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test basic compatibility across all supported Python versions. We
          # only do this on Linux to reduce the GitHub actions cost.
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.9"
            os-type: linux
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.10"
            os-type: linux
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.11"
            os-type: linux
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.12"
            os-type: linux
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.13"
            os-type: linux
          - os: ubuntu-latest
            include-optionals: false
            python-version: "3.14"
            os-type: linux

          # Perform all tests on the three supported operating systems, for the
          # one recent Python version.
          - os: ubuntu-latest
            include-optionals: true
            python-version: "3.12"
            os-type: linux
          - os: macos-latest
            include-optionals: true
            python-version: "3.12"
            os-type: macos
          - os: windows-latest
            include-optionals: true
            python-version: "3.12"
            os-type: windows

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install required dependencies
      run: |
        python -m pip install --root-user-action=ignore --upgrade pip
        python -m pip install --root-user-action=ignore -r requirements.txt
        python -m pip install --root-user-action=ignore -r dev-requirements.txt

    - name: Lint with ruff
      if: matrix.include-optionals
      uses: chartboost/ruff-action@v1

    - name: Base tests with tox
      if: ${{ !matrix.include-optionals }}
      run: tox -e py${{ matrix.python-version }}-base-${{ matrix.os-type }} -- -lvv --maxfail=5 -m 'not slow'

    - name: All tests with tox
      if: ${{ matrix.include-optionals }}
      run: tox -e py${{ matrix.python-version }}-all-${{ matrix.os-type }} -- -lvv --maxfail=5 -m 'not slow'
